2025-02-25 10:26:21,819 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 10:27:53,388 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 10:40:11,976 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 10:43:39,305 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 10:55:13,406 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 10:56:45,327 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 11:00:48,171 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:71]
2025-02-25 11:24:41,467 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:55]
2025-02-25 11:27:18,192 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:55]
2025-02-25 11:33:36,776 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:55]
2025-02-25 11:36:04,027 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:55]
2025-02-25 11:37:49,403 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:55]
2025-02-25 11:38:20,607 ERROR: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
Traceback (most recent call last):
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-02-25 11:38:20,800 ERROR: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
Traceback (most recent call last):
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-02-25 11:38:39,326 ERROR: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
Traceback (most recent call last):
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/martin/Documents/EigeneProjekte/Website/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 11:53:48,998] INFO in __init__: Dartochsen startup
[2025-02-25 11:53:49,016] WARNING in _internal:  * Debugger is active!
[2025-02-25 11:53:49,024] INFO in _internal:  * Debugger PIN: 137-281-515
[2025-02-25 11:54:28,282] ERROR in __init__: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 11:54:28,283] INFO in _internal: 127.0.0.1 - - [25/Feb/2025 11:54:28] "[33mGET / HTTP/1.1[0m" 404 -
[2025-02-25 11:55:08,373] INFO in _internal:  * Detected change in '/Users/martin/kuellstedter-dartochsen/config.py', reloading
[2025-02-25 11:55:10,014] INFO in __init__: Dartochsen startup
[2025-02-25 11:55:10,034] WARNING in _internal:  * Debugger is active!
[2025-02-25 11:55:10,044] INFO in _internal:  * Debugger PIN: 137-281-515
[2025-02-25 11:55:25,853] ERROR in __init__: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 11:55:25,855] INFO in _internal: 127.0.0.1 - - [25/Feb/2025 11:55:25] "[33mGET / HTTP/1.1[0m" 404 -
[2025-02-25 12:04:42,786] INFO in __init__: Dartochsen startup
[2025-02-25 12:04:42,790] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-02-25 12:04:42,790] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-02-25 12:04:55,039] ERROR in __init__: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 12:04:55,041] INFO in _internal: 127.0.0.1 - - [25/Feb/2025 12:04:55] "[33mGET / HTTP/1.1[0m" 404 -
[2025-02-25 12:04:55,401] ERROR in __init__: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 12:04:55,401] INFO in _internal: 127.0.0.1 - - [25/Feb/2025 12:04:55] "[33mGET / HTTP/1.1[0m" 404 -
[2025-02-25 12:06:29,782] INFO in __init__: Dartochsen startup
[2025-02-25 12:06:29,806] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-02-25 12:06:29,806] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-02-25 12:06:29,807] INFO in _internal:  * Restarting with stat
[2025-02-25 12:06:30,775] INFO in __init__: Dartochsen startup
[2025-02-25 12:06:30,793] WARNING in _internal:  * Debugger is active!
[2025-02-25 12:06:30,801] INFO in _internal:  * Debugger PIN: 137-281-515
[2025-02-25 12:06:33,021] ERROR in __init__: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 12:06:33,026] INFO in _internal: 127.0.0.1 - - [25/Feb/2025 12:06:33] "[33mGET / HTTP/1.1[0m" 404 -
[2025-02-25 12:10:34,690] INFO in _internal:  * Detected change in '/Users/martin/kuellstedter-dartochsen/app/main/routes.py', reloading
[2025-02-25 12:10:34,901] INFO in _internal:  * Restarting with stat
[2025-02-25 12:10:36,256] INFO in __init__: Dartochsen startup
[2025-02-25 12:10:36,280] WARNING in _internal:  * Debugger is active!
[2025-02-25 12:10:36,288] INFO in _internal:  * Debugger PIN: 137-281-515
[2025-02-25 12:11:35,888] INFO in _internal:  * Detected change in '/Users/martin/kuellstedter-dartochsen/app/main/routes.py', reloading
[2025-02-25 12:11:36,096] INFO in _internal:  * Restarting with stat
[2025-02-25 12:11:37,366] INFO in __init__: Dartochsen startup
[2025-02-25 12:11:37,386] WARNING in _internal:  * Debugger is active!
[2025-02-25 12:11:37,393] INFO in _internal:  * Debugger PIN: 137-281-515
[2025-02-25 12:11:41,013] ERROR in __init__: 404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-25 12:11:41,018] INFO in _internal: 127.0.0.1 - - [25/Feb/2025 12:11:41] "[33mGET / HTTP/1.1[0m" 404 -
[2025-02-25 12:13:30,551] INFO in _internal:  * Detected change in '/Users/martin/kuellstedter-dartochsen/app/main/__init__.py', reloading
[2025-02-25 12:13:30,736] INFO in _internal:  * Restarting with stat
[2025-02-25 12:13:31,986] INFO in __init__: Dartochsen startup
[2025-02-25 12:13:32,003] WARNING in _internal:  * Debugger is active!
[2025-02-25 12:13:32,010] INFO in _internal:  * Debugger PIN: 137-281-515
[2025-02-25 12:14:43,756] INFO in _internal:  * Detected change in '/Users/martin/kuellstedter-dartochsen/app/__init__.py', reloading
[2025-02-25 12:14:43,976] INFO in _internal:  * Restarting with stat
